# Copyright (C) 2017 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/samsung/msm7x27a-common/setup-makefiles.sh

PRODUCT_COPY_FILES +=   vendor/samsung/msm7x27a-common/proprietary/lib/libril-qcril-hook-oem.so:system/lib/libril-qcril-hook-oem.so
PRODUCT_COPY_FILES +=   vendor/samsung/msm7x27a-common/proprietary/lib/libril-qc-1.so:system/lib/libril-qc-1.so
PRODUCT_COPY_FILES +=   vendor/samsung/msm7x27a-common/proprietary/lib/libril-qc-qmi-1.so:system/lib/libril-qc-qmi-1.so
PRODUCT_COPY_FILES +=   vendor/samsung/msm7x27a-common/proprietary/lib/libreference-ril.so:system/lib/libreference-ril.so
PRODUCT_COPY_FILES +=   vendor/samsung/msm7x27a-common/proprietary/lib/libqmi_client_qmux.so:system/lib/libqmi_client_qmux.so
PRODUCT_COPY_FILES +=   vendor/samsung/msm7x27a-common/proprietary/lib/libdualsimswitch.so:system/lib/libdualsimswitch.so
PRODUCT_COPY_FILES +=   vendor/samsung/msm7x27a-common/proprietary/lib/libdsutils.so:system/lib/libdsutils.so
PRODUCT_COPY_FILES +=   vendor/samsung/msm7x27a-common/proprietary/lib/libdsprofile.so:system/lib/libdsprofile.so
PRODUCT_COPY_FILES +=   vendor/samsung/msm7x27a-common/proprietary/lib/libdss.so:system/lib/libdss.so
PRODUCT_COPY_FILES +=   vendor/samsung/msm7x27a-common/proprietary/lib/libdsm.so:system/lib/libdsm.so
PRODUCT_COPY_FILES +=   vendor/samsung/msm7x27a-common/proprietary/lib/libdsi_netctrl.so:system/lib/libdsi_netctrl.so
PRODUCT_COPY_FILES +=   vendor/samsung/msm7x27a-common/proprietary/lib/liboncrpc.so:system/lib/liboncrpc.so
PRODUCT_COPY_FILES +=   vendor/samsung/msm7x27a-common/proprietary/lib/libqcci_legacy.so:system/lib/libqcci_legacy.so
PRODUCT_COPY_FILES +=   vendor/samsung/msm7x27a-common/proprietary/lib/libqdi.so:system/lib/libqdi.so
PRODUCT_COPY_FILES +=   vendor/samsung/msm7x27a-common/proprietary/lib/libmmgsdilib.so:system/lib/libmmgsdilib.so
PRODUCT_COPY_FILES +=   vendor/samsung/msm7x27a-common/proprietary/lib/libwms.so:system/lib/libwms.so
PRODUCT_COPY_FILES +=   vendor/samsung/msm7x27a-common/proprietary/lib/libqmiservices.so:system/lib/libqmiservices.so
PRODUCT_COPY_FILES +=   vendor/samsung/msm7x27a-common/proprietary/lib/libidl.so:system/lib/libidl.so
PRODUCT_COPY_FILES +=   vendor/samsung/msm7x27a-common/proprietary/lib/libqdp.so:system/lib/libqdp.so
PRODUCT_COPY_FILES +=   vendor/samsung/msm7x27a-common/proprietary/lib/libcneqmiutils.so:system/lib/libcneqmiutils.so
PRODUCT_COPY_FILES +=   vendor/samsung/msm7x27a-common/proprietary/lib/libqmi_csvt_srvc.so:system/lib/libqmi_csvt_srvc.so
PRODUCT_COPY_FILES +=   vendor/samsung/msm7x27a-common/proprietary/lib/libcnefeatureconfig.so:system/lib/libcnefeatureconfig.so
PRODUCT_COPY_FILES +=   vendor/samsung/msm7x27a-common/proprietary/lib/libcneutils.so:system/lib/libcneutils.so
PRODUCT_COPY_FILES +=   vendor/samsung/msm7x27a-common/proprietary/lib/libuim.so:system/lib/libuim.so
PRODUCT_COPY_FILES +=   vendor/samsung/msm7x27a-common/proprietary/lib/libgsdi_exp.so:system/lib/libgsdi_exp.so
PRODUCT_COPY_FILES +=   vendor/samsung/msm7x27a-common/proprietary/lib/libcm.so:system/lib/libcm.so
PRODUCT_COPY_FILES +=   vendor/samsung/msm7x27a-common/proprietary/lib/libqmi.so:system/lib/libqmi.so
PRODUCT_COPY_FILES +=   vendor/samsung/msm7x27a-common/proprietary/lib/libauth.so:system/lib/libauth.so
PRODUCT_COPY_FILES +=   vendor/samsung/msm7x27a-common/proprietary/lib/libcneapiclient.so:system/lib/libcneapiclient.so
PRODUCT_COPY_FILES +=   vendor/samsung/msm7x27a-common/proprietary/lib/libgstk_exp.so:system/lib/libgstk_exp.so
PRODUCT_COPY_FILES +=   vendor/samsung/msm7x27a-common/proprietary/lib/libpbmlib.so:system/lib/libpbmlib.so
PRODUCT_COPY_FILES +=   vendor/samsung/msm7x27a-common/proprietary/lib/libwmsts.so:system/lib/libwmsts.so
PRODUCT_COPY_FILES +=   vendor/samsung/msm7x27a-common/proprietary/lib/libping_mdm.so:system/lib/libping_mdm.so
PRODUCT_COPY_FILES +=   vendor/samsung/msm7x27a-common/proprietary/lib/libhwrpc.so:system/lib/libhwrpc.so
PRODUCT_COPY_FILES +=   vendor/samsung/msm7x27a-common/proprietary/lib/liboemcamera.so:system/lib/liboemcamera.so
PRODUCT_COPY_FILES +=   vendor/samsung/msm7x27a-common/proprietary/bin/qmuxd:system/bin/qmuxd
PRODUCT_COPY_FILES +=   vendor/samsung/msm7x27a-common/proprietary/bin/qmiproxy:system/bin/qmiproxy
PRODUCT_COPY_FILES +=   vendor/samsung/msm7x27a-common/proprietary/bin/netmgrd:system/bin/netmgrd
